### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [DavidBerdik/MACsposed#8]
...as  libxposed not yet in ([trusted](https://gitlab.com/fdroid/fdroidserver/-/blob/2a60f6c195dfd24149617ceb1df1731fb3bf50c8/fdroidserver/scanner.py#L452-L471)) maven repos

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5268128216#L511

ref: https://github.com/LSPosed/LSPosed/wiki/Develop-Xposed-Modules-Using-Modern-Xposed-API/a7f346f7ec01ea698e1b187fc20de5fc727b0d09#early-access

/LE: https://gitlab.com/fdroid/fdroiddata/-/commit/c2bcebc2e6eee7d444da8afc49f442007b95f1bf fyi

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/4da6b70bad4b169b626e29f6ebe6ee8af84bc56e

**Comment by DavidBerdik** [comment]
At the time of release, I had actually forgotten that this was probably going to be an issue for F-Droid.

Is there any course of action that can be taken by someone on the F-Droid team to work around this until the library is formally published?

**Comment by licaon-kter** [comment]
Besides build from source?/

**Comment by DavidBerdik** [comment]
Well, currently, there is no way to access the libraries other than to build them from source and then use `gradle publishToMavenLocal` ([reference](https://github.com/libxposed/service/issues/4#issuecomment-1454364434)). If the team is okay with doing that, then both of my modules should be able to build without any issues.

**Comment by licaon-kter** [comment]
Yes, there are many recipes that use that.

**Comment by DavidBerdik** [comment]
Great! Could that approach then please be used for these two apps? It should only be necessary for as long as the libraries are not available in the Maven repo. That said, I have no idea how long it's going to be until the LSPosed team makes them available.

**Comment by DavidBerdik** [comment]
@licaon-kter Is there any further action required from me in order to resolve this?

**Comment by licaon-kter** [comment]
Not for now, I tested yesterday but it run out of memory iirc, so I need to bump gradle stuff, will post back when I get further.

**Comment by DavidBerdik** [comment]
Excellent. Thank you!

**Comment by licaon-kter** [comment]
Trying this recipe:
```
  - versionName: 1.1.5
    versionCode: 8
    commit: 851e0bb814be649a28fcbb81aa4daa07e4cbcba2
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    gradle:
      - yes
    prebuild:
      - echo -e "\norg.gradle.jvmargs=-Xmx4096m" >> ../gradle.properties
      - echo -e "\norg.gradle.jvmargs=-XX:MaxHeapSize=2048m" >> ../gradle.properties
    build:
      - git clone https://github.com/libxposed/api
      - pushd api
      - git checkout -f 100
      - gradle publishToMavenLocal
      - popd
      - git clone https://github.com/libxposed/service
      - pushd api
      - git checkout -f 100
      - gradle publishToMavenLocal
      - popd
```
...it takes a lot of time to build service, eg. I let it run overnight and 19h later it was not done :(
